stages:
  train:
    cmd: python -m pipeline.pipeline
    deps:
      - data/train.csv
      - src/train.py
      - src/features.py
      - src/preprocess.py
    params:
      - random_forest
      - xgboost
    outs:
      - models/model_v1.pkl